### ISSUE TITLE
Could you please give the detailed information about Ensemble?

### ISSUE THREAD

**Issue by longmalongma** [hkchengrex/STCN#42]
After I added ASPP and Wideresnet50 to your code, the segmentation accuracy decreased. Could you please give the detailed information about Ensemble?

**Comment by JerryX1110** [comment]
Without using BL30K data, I tried to use resnet101+aspp, resnet101w+aspp, and resnet50w+aspp, the performance on YTB all dropped lightly. I am not quite sure of whether I need to tune the hypers more carefully for better performance. Have you used BL30K data? @longmalongma

**Comment by longmalongma** [comment]
> Without using BL30K data, I tried to use resnet101+aspp, resnet101w+aspp, and resnet50w+aspp, the performance on YTB all dropped lightly. I am not quite sure of whether I need to tune the hypers more carefully for better performance. Have you used BL30K data? @longmalongma

@JerryX1110 Yes, I tried to use resnet101+aspp, resnet101w+aspp, and resnet50w+aspp with BL30K, the performance on YTB all also dropped lightly.  That's why I brought it up.

**Comment by hkchengrex** [comment]
@JerryX1110 @longmalongma Sorry that I could not be more responsive these days since I am moving and there is a lot to handle.

From my experience changing the backbone from resnet50 to wide-resnet50 always helps. Adding ASPP or using a deeper network does not always help because it changes the receptive field and you might need a larger crop size in training.

**Comment by hkchengrex** [comment]
Just to clarify -- I did not use a larger crop size in my experiments for models with ASPP because it's so much slower to train. That's just a suggestion.
